composer.json

Fixed the composer setup to require php and cakephp so that the test suite can be run properly independently

Updates to composer

---

README.md
src/Event/ProfferListener.php
src/Model/Behavior/ProfferBehavior.php

* Re-ordered the event methods so the signatures are similar allowing a custom listener to assume the first two arguments
* Fixed a minor typo in the readme
* Added more documentation about the configuration options
* Added an example of replacing the event listener

Number of fixes

---

README.md
src/Lib/ImageTransform.php
src/Lib/ImageTransformInterface.php
src/Lib/ProfferPath.php
src/Model/Behavior/ProfferBehavior.php

* Created a new interface for `ImageTransform` so that it can be refactored to be swappable
* Added a new event, allowing users to hook all the data on where the file will be stored

New event and interface

---

.travis.yml
src/Model/Behavior/ProfferBehavior.php

Removed the need to rely on PEAR to load things in Travis

Remove PEAR dependancy

---

.travis.yml
src/Model/Behavior/ProfferBehavior.php
src/Model/Validation/ProfferRules.php
tests/TestCase/Model/Behavior/ProfferBehaviorTest.php
tests/TestCase/Model/Validation/ProfferRulesTest.php

Merge for latest release.
* Lots more tests to help strengthen the testing
* Minor bugfix to validation
* Restructuring the events

Merge for release

---

src/Database/Type/FileType.php

Fix a bug introduced when the data type casting of arrays was changed in the core. Instead of dealing with how things are passed, can just make sure the data isn't cast in the entity marshalling process.

Resolves #79

---

src/Model/Behavior/ProfferBehavior.php
tests/TestCase/Model/Behavior/ProfferBehaviorTest.php

Wrapped the various file system methods to check for existence first, and added a matching test.

Resolves #77. 

---

docs/configuration.md
src/Lib/ProfferPath.php
src/Model/Behavior/ProfferBehavior.php
tests/TestCase/Model/Behavior/ProfferBehaviorTest.php

Relates to #78
Allowed the behaviour to be configured to not create thumbnails by omitting the thumbnailSizes configuration.

Make thumbnail generation optional

---

docs/customisation.md
docs/examples/UploadFilenameListener.md
src/Lib/ProfferPath.php
tests/TestCase/Model/Behavior/ProfferBehaviorTest.php

Allowed the table part of the path to be customised in the event listener, also added appropriate test and documentation.

Resolves #72

---

src/Lib/ProfferPath.php
tests/TestCase/Model/Behavior/ProfferBehaviorTest.php

This change allows for certain path elements to be empty, and also adds relevant tests.

Allow empty path

---

src/Shell/ProfferShell.php

Now default bin/cake proffer command works like bin/cake proffer -h command

Improved shell default messages

---

README.md
docs/customisation.md
docs/examples.md
docs/examples/UploadFilenameListener.md
docs/shell.md
src/Lib/ImageTransform.php
src/Shell/ProfferShell.php

Merging updates

---

src/Lib/ProfferPath.php
src/Model/Behavior/ProfferBehavior.php

Resolve #121. Resolve #120. Resolve #119.

Implements webme's fixes

---

docs/configuration.md
src/Lib/ImageTransform.php

Hello,
I needed to set jpeg_quality of generated thumbnails in one of my projects. I thought that this functionality will be useful for others also. This as well provide control over other settings sending to Imagine save method.
Best Regards,
Kamoris

Functionality to set jpeg_quality and other options for thumbnails

---

docs/faq.md

Please correct My English if not appropriate :)
Or delete the section?

Fix faq.md explains old version instructions

---

docs/customisation.md
docs/examples.md
docs/examples/UploadAndDeleteImageListener.md
src/Lib/ImageTransform.php
src/Lib/ImageTransformInterface.php
src/Model/Behavior/ProfferBehavior.php
tests/TestCase/Model/Behavior/ProfferBehaviorTest.php

Hello,
In this PR, I want to hook creation and deletion of files for uploading to other service (Amason S3, etc).
So I added functions which dispatch "Proffer.afterCreateImage" and "Proffer.beforeDeleteFolder" events to beforeSave and afterDelete.
Thank you.

Add dispatching file creation and deletion event

---

docs/customisation.md
docs/examples.md
docs/examples/UploadAndDeleteImageListener.md
src/Lib/ImageTransform.php
src/Lib/ImageTransformInterface.php
src/Model/Behavior/ProfferBehavior.php
tests/TestCase/Model/Behavior/ProfferBehaviorTest.php

Hello,
I'm sorry that I have mistake in commit author in https://github.com/davidyell/CakePHP3-Proffer/pull/158 .
So please merge this PR and close https://github.com/davidyell/CakePHP3-Proffer/pull/158 .
Sorry for inconvenient.
As I said in https://github.com/davidyell/CakePHP3-Proffer/pull/158 , 
I have updated documents and examples.
Please check them.
Thank you.

(fix)Add dispatching file creation and deletion event

---

src/Shell/ProfferShell.php

https://github.com/davidyell/CakePHP3-Proffer/issues/163
I tested code in my own project.
But if I need more test, please instruct me.
thank you.

fix cleanup for when model has multiple proffer columns #163

---

docs/configuration.md

See https://github.com/davidyell/CakePHP3-Proffer/pull/177

Add missing comma

---

.coveralls.yml
.travis.yml
composer.json
phpunit.xml

Trying to fix coveralls.
First TRRYYY!

Resolves #204

---

docs/installation.md

Need to pull in the latest changes from `develop` branch into `master` for any new users installing the plugin.

Merge for update

---

src/Lib/ImageTransform.php

- keep aspect ratio when resizing with no option.

Add keep aspect ratio setting when resize with no option

---

composer.json
docs/installation.md
tests/TestCase/Lib/ProfferPathTest.php
tests/TestCase/Model/Behavior/ProfferBehaviorTest.php
tests/TestCase/Model/Validation/ProfferRulesTest.php
tests/bootstrap.php

A few minor updates for the 4.x future release.
Also updated the test cases

Fixes for 4.x compatibility

---

README.md
src/Database/Type/FileType.php
src/Model/Behavior/ProfferBehavior.php
src/Model/Validation/ProfferRules.php
tests/TestCase/Model/Validation/ProfferRulesTest.php

https://github.com/davidyell/CakePHP-Proffer/commit/805e99edc554a32b6797796d612e57c8f686690a looks a little bit messy in the diff, but the only code changed is line 189-191 (swapping the if order and return early), the rest is indentation fluff.

Small fixes and improvments for CakePHP 4
